services:
  - type: web
    name: telegram-userbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: STRING_SESSION
        value: your_string_here
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
